
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjqbekiloqgkmbrgrdho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqcWJla2lsb3Fna21icmdyZGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDQwMTYsImV4cCI6MjA1ODgyMDAxNn0.bKHNxaD0BxJ_r0EiM-Vf20bpIfusbpHxip8mrFoeXH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
